config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
  get 'warehouses/:id/confirmar_exclusao', to: 'warehouses#confirmar_exclusao', as: 'confirmar_exclusao'
  resources :suppliers, only: [:index, :new, :create, :show, :edit, :update]
  resources :product_models, only:[:index, :new, :create, :show]

  resources :orders, only:[:new, :create, :show, :index, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member

  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user
  enum status: {pending: 0 , delivered: 5, canceled: 7}

  validates :code, :estimated_delivery_date, presence: true
  validate :estimated_delivery_date_is_future
  before_validation :generate_code

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  def estimated_delivery_date_is_future
    if self.estimated_delivery_date.present? && self.estimated_delivery_date <= Date.today
      self.errors.add(:estimated_delivery_date, ' deve ser futura.')
    end
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier

  def full_dimensions
    "#{height}cm X #{width}cm X #{depth}cm"
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates  :corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email, presence: true

  def full_register
    "#{corporate_name} | #{registration_number}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders

  def description
    "#{name} - #{email}"
  end
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord

  validates  :name, :code, :city, :area, :description, :cep, :address, presence: true
  validates :code, uniqueness: true

  def full_description
    "#{code} | #{name}"
  end
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API
  rescue_from ActiveRecord::ActiveRecordError, with: :return_500
  rescue_from ActiveRecord::RecordNotFound, with: :return_404

  def return_500
    render status: 500
  end

  def return_404
    render status: 404
  end
end

app/controllers/api/v1/warehouses_controller.rb
class Api::V1::WarehousesController < Api::V1::ApiController

  def show
    warehouse = Warehouse.find(params[:id])
    render status: 200, json: warehouse.as_json(except: [:created_at, :updated_at])
  end

  def index
    warehouses = Warehouse.all.order(:name)
    render status: 200, json: warehouses.as_json(except: [:created_at, :updated_at])
  end

  def create
    warehouse_params = params.require(:warehouse).permit(:name, :code, :city, :address, :cep, :area, :description)
    warehouse = Warehouse.new(warehouse_params)
    if warehouse.save
      render status: 201, json: warehouse
    else
      render status: 412, json: { errors: warehouse.errors.full_messages}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @warehouses = Warehouse.all
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order_and_check_user, only: %i[show edit update delivered canceled]
  def new
    @order = Order.new
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def create
    order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
    @order = Order.new(order_params)
    @order.user = current_user

    if @order.save
      @order.pending!
      redirect_to @order, notice: 'Pedido registrado com sucesso.'
    else
      @warehouses = Warehouse.all
      @suppliers = Supplier.all
      flash.now[:alert] = 'Não foi possivel registrar o pedido.'
      render :new
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def edit
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def update
    order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
    @order.update(order_params)
    redirect_to @order, notice: 'Pedido atualizado com sucesso'
  end

  def index
    @orders = current_user.orders
  end

  def search
    @code = params['query']
    @orders = Order.where("code LIKE ?", "%#{@code}%")

  end

  def delivered
    @order.delivered!
    redirect_to @order
  end

  def canceled
    @order.canceled!
    redirect_to @order
  end

  private

  def set_order_and_check_user
    @order = Order.find(params[:id])
    if @order.user != current_user
      redirect_to root_path, notice: 'Você não possui acesso a este pedido'
    end
  end
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only:[:index]

  def index
    @product_models = ProductModel.all
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    @product_model = ProductModel.new(product_model_params)

    if @product_model.save
      redirect_to @product_model, notice: 'Modelo de produto cadastrado com sucesso'
    else
      flash[:notice] = 'Falha ao cadastrar modelo de produto'
    end

  end

  def show
    @product_model = ProductModel.find(params[:id])
  end
end


private

def product_model_params
  product_model_params = params.require(:product_model).permit(:name, :height, :width, :depth, :weight, :sku, :supplier_id)
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController

  before_action :set_supplier, only:[:show, :edit, :update]

  def index
    @suppliers = Supplier.all
    if @suppliers.empty?
      flash[:notice] = 'Não existem fornecedores cadastrados'
    end
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)

    if @supplier.save()
      redirect_to supplier_path(@supplier.id), notice: 'Fornecedor cadastrado com sucesso'
    else
      flash.now[:notice] = 'Fornecedor não cadastrado'
      render 'new'
    end

  end

  def show; end

  def edit; end

  def update
    if @supplier.update(supplier_params)
      redirect_to supplier_path(@supplier.id), notice: 'Fornecedor atualizado com sucesso'
    else
      flash[:notice] = 'Fornecedor não atualizado'
      render 'edit'
    end
  end

  private

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    supplier_params = params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number,
                                                        :full_address, :city, :state, :email)
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController

    before_action :set_warehouse, only: [:show, :edit, :update, :destroy]

    def show; end

    def new
        @warehouse = Warehouse.new
    end

    def create
        @warehouse = Warehouse.new(warehouse_params)
        if @warehouse.save()
            redirect_to root_path, notice: 'Galpao cadastrado com sucesso.'
        else
            flash.now[:notice] = 'Galpao nao cadastrado'
            render 'new'
        end
    end

    def edit; end

    def update
        if @warehouse.update(warehouse_params)
            redirect_to warehouse_path(@warehouse.id), notice: 'Galpão atualizado com sucesso'
        else
            flash[:notice] = 'Não foi possível atualizar o galpão'
            render 'edit'
        end
    end

    def destroy
        @warehouse.destroy
        redirect_to root_path, notice: 'Galpão removido com sucesso'
    end

    def confirmar_exclusao
        set_warehouse
    end

    private

    def set_warehouse
        @warehouse = Warehouse.find(params[:id])
    end

    def warehouse_params
        params.require(:warehouse).permit(:name, :code,  :city, :description,
                                        :address, :cep, :area)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<section>
  <h2>Galpoes</h2>

  <div>
    <%= link_to('Cadastrar Galpao', new_warehouse_path )%>
  </div>
  <% @warehouses.each do |w|%>
    <h3><%= link_to(w.name, warehouse_path(w.id)) %></h3>
    <dl>
      <dt> Codígo:
      <dd><%= w.code %></dd>
      <dt> Cidade: </dt>
      <dd><%= w.city %></dd>
      <dt> Área: </dt>
      <dd><%= w.area%> m2</dd>
    </dl>
  <% end %>


  <% if @warehouses.empty? %>
    <p>Nao existem galpoes cadastrados</p>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <h1><%= link_to('Galpoes & Estoque', root_path)  %></h1>
      <nav>
        <%= link_to('Página Inicial', root_path)%> |
        <%= link_to('Fornecedores', suppliers_path) %> |
        <%= link_to('Modelos de Produtos', product_models_path)%> |
        <%= link_to('Registrar Pedido', new_order_path)%> |
        <%= link_to('Meus Pedidos', orders_path)%> |

        <% if user_signed_in? %>
          <%= form_with(url: search_orders_path , method: :get) do |f|%>
            <%= f.label :query, 'Buscar Pedido' %>
            <%= f.text_field :query %>
            <%= f.submit 'Buscar'%>
          <% end %>
        <% end %>


        <% if user_signed_in? %>
          <%= current_user.description %> |
          <%= button_to 'Sair', destroy_user_session_path, method: :delete%>|
        <% else %>
          <%= link_to('Entrar', new_user_session_path)%> |
        <% end %>
      </nav>
    </header>

    <div>
      <%= flash[:notice] %>
      <%= flash[:alert] %>
    </div>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: @order) do | f |%>

  <div>
    <%= f.label :warehouse_id%>
    <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description %>
  </div>

  <div>
    <%= f.label :supplier_id%>
    <%= f.collection_select :supplier_id, @suppliers, :id, :corporate_name %>
  </div>

  <div>
    <%= f.label :estimated_delivery_date%>
    <%= f.date_field :estimated_delivery_date %>
  </div>

  <div>
    <%= f.submit 'Salvar'%>
  </div>


<% end %>

app/views/orders/_order.html.erb
<dl>
  <dt><%=Order.human_attribute_name(:code)%>:</dt>
  <dd><%= link_to order.code, order %></dd>
  <dt><%=Order.human_attribute_name(:warehouse_id)%>:</dt>
  <dd><%=order.warehouse.full_description %></dd>
  <dt><%=Order.human_attribute_name(:supplier_id)%>:</dt>
  <dd><%=order.supplier.corporate_name%></dd>
  <dt><%=Order.human_attribute_name(:status)%>:</dt>
  <dd><%=I18n.translate(order.status)%></dd>
</dl>

app/views/orders/edit.html.erb
<h1>Editar Pedido</h1>
<%= render 'form' %>

app/views/orders/index.html.erb
<h1>Meus Pedidos</h1>

<% @orders.each do |order| %>
  <%= render order %>
<% end %>

app/views/orders/new.html.erb
<h1>Registre seu pedido</h1>

<%= render 'form' %>

app/views/orders/search.html.erb
<h1>Resultados da busca por: <%= @code %></h1>

<p><%= @orders.count %> <%= Order.model_name.human(count: @orders.count).downcase%>
<%= I18n.t(:found, count: @orders.count).downcase%> </p>
<% @orders.each do |order|%>
  <dl>
    <%= render order %>
  </dl>
<% end %>

app/views/orders/show.html.erb
<h1> Detalhes do pedido </h1>
<h2><%= Order.model_name.human %> <%= @order.code%></h2>
<dl>
  <dt><%= Order.human_attribute_name(:user_id)%>:</dt>
  <dd><%=@order.user.description%></dd>

  <dt><%= Order.human_attribute_name(:warehouse_id)%>:</dt>
  <dd><%=@order.warehouse.full_description%></dd>

  <dt><%= Order.human_attribute_name(:supplier_id)%>:</dt>
  <dd><%=@order.supplier.full_register%></dd>


  <dt><%= Order.human_attribute_name(:estimated_delivery_date)%>:</dt>
  <dd><%= I18n.localize(@order.estimated_delivery_date)%></dd>

  <dt><%= Order.human_attribute_name(:status)%>:</dt>
  <dd><%= I18n.translate(@order.status)%></dd>

  <% if @order.pending? %>
    <%= button_to 'Marcar como Entregue', delivered_order_path(@order.id) %>
    <%= button_to 'Marcar como Cancelado', canceled_order_path(@order.id) %>
  <% end %>

</dl>

<%= link_to 'Editar', edit_order_path(@order.id)%>

app/views/product_models/index.html.erb
<h1><%= ProductModel.model_name.human%></h1>
<%= link_to('Cadastrar novo', new_product_model_path)%>
<% if @product_models.any? %>
  <%= @product_models.each do |p|%>
    <div>
      <h2><%= p.name %></h2>
      <dl>
        <dt><%= ProductModel.human_attribute_name(:sku)%></dt>
        <dd><%= p.sku %></dd>
        <dt><%= Supplier.human_attribute_name(:supplier)%></dt>
        <dd><%= p.supplier.full_register %></dd>
      </dl>
    </div>
  <% end %>
<% else %>
  <p> Nenhum modelo de produto cadastrado. </p>
<% end %>

app/views/product_models/new.html.erb
<h1>Cadastrar Modelo de Produto </h1>

<%= form_with(model: @product_model) do | f |%>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>

  <div>
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>

  <div>
    <%= f.label :width %>
    <%= f.number_field :width %>
  </div>

  <div>
    <%= f.label :depth %>
    <%= f.number_field :depth %>
  </div>

  <div>
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>

  <div>
    <%= f.label :supplier_id%>
    <%= f.collection_select :supplier_id, @suppliers, :id, :full_register %>
  </div>

  <%= f.submit 'Enviar' %>

<% end %>

app/views/product_models/show.html.erb
<h1><%= @product_model.name %></h1>

<div>
  <dl>
    <dt><%= ProductModel.human_attribute_name(:supplier_id)%>:</dt>
    <dd><%= @product_model.supplier.full_register %></dd>
  </dl>

  <dl>
    <dt><%= ProductModel.human_attribute_name(:sku)%>:</dt>
    <dd><%= @product_model.sku %></dd>
  </dl>

  <dl>
    <dt><%= ProductModel.human_attribute_name(:dimensions)%>:</dt>
    <dd><%= @product_model.full_dimensions%></dd>
  </dl>

  <dl>
    <dt><%= ProductModel.human_attribute_name(:weight)%>:</dt>
    <dd><%= @product_model.weight %>g</dd>
  </dl>


</div>

app/views/suppliers/_form.html.erb
<%= form_with(model: @supplier) do |s| %>
  <div>
    <%= s.label :corporate_name%>
    <%= s.text_field :corporate_name%>
  </div>

  <div>
    <%= s.label :brand_name%>
    <%= s.text_field :brand_name%>
  </div>

  <div>
    <%= s.label :registration_number%>
    <%= s.text_field :registration_number%>
  </div>

  <div>
    <%= s.label :full_address%>
    <%= s.text_field :full_address%>
  </div>

  <div>
    <%= s.label :city%>
    <%= s.text_field :city%>
  </div>

  <div>
    <%= s.label :state%>
    <%= s.text_field :state%>
  </div>

  <div>
    <%= s.label :email%>
    <%= s.text_field :email%>
  </div>
  <%= s.submit 'Enviar' %>

<% end %>

app/views/suppliers/edit.html.erb
<h1>Editar Fornecedor</h1>

<div>
  <%= render 'form' %>
</div>

app/views/suppliers/index.html.erb
<h1>Fornecedores</h1>

<% @suppliers.each do | s |%>
  <div>
    <dl>
      <dt>
       <strong><%= Supplier.model_name.human%>:</strong>
      </dt>
      <%= link_to(s.full_register) %>
      <%= link_to('Editar', edit_supplier_path(s.id))%>
    </dl>
  </div>
<% end %>

<div>
  <%= link_to('Cadastrar Fornecedor', new_supplier_path)%>
  <%= link_to('Voltar', root_path)%>
</div>

app/views/suppliers/new.html.erb
<h1>Cadastrar um Fornecedor</h1>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<h1>Detalhes do Fornecedor <%= @supplier.brand_name %></h1>

<div>
  <dt><%= Supplier.human_attribute_name(:full_register)%>:</dt>
  <dd><%= @supplier.full_register %></dd>
  <dt><%= Supplier.human_attribute_name(:brand_name)%>:</dt>
  <dd><%= @supplier.brand_name %></dd>
  <dt><%= Supplier.human_attribute_name(:full_address)%>:</dt>
  <dd><%= @supplier.full_address %></dd>
  <dt><%= Supplier.human_attribute_name(:city)%>:</dt>
  <dd><%= @supplier.city %></dd>
  <dt><%= Supplier.human_attribute_name(:state)%>:</dt>
  <dd><%= @supplier.state %></dd>
  <dt><%= Supplier.human_attribute_name(:email)%>:</dt>
  <dd><%= @supplier.email %></dd>
</div>

<div>
  <%= link_to('Editar', edit_supplier_path(@supplier.id))%>
</div>

app/views/warehouses/_form.html.erb
<%= form_with(model: @warehouse) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :cep %>
    <%= f.text_field :cep %>
  </div>

  <div>
    <%= f.label :area %>
    <%= f.number_field :area %>
  </div>

  <%= f.submit 'Enviar'%>
<% end %>

app/views/warehouses/confirmar_exclusao.html.erb
<h1>Confirmação de exclusão</h1>
<p>Tem certeza que deseja excluir este objeto?</p>
<%= form_with url: warehouse_path(@warehouse.id), method: :delete do |f| %>
  <%= f.submit "Confirmar exclusão" %>
  <%= link_to "Cancelar", warehouse_path(@warehouse.id) %>
  <% link_to 'Confirmar', root_path%>
<% end %>

app/views/warehouses/edit.html.erb
<h1>Editar Galpão</h1>

<%= render 'form' %>

app/views/warehouses/new.html.erb
<h1>Novo Galpao</h1>

<% if(@warehouse.errors.any?) %>
  <p> Verifique os erros abaixo: </p>
  <ul>
    <% @warehouse.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/warehouses/show.html.erb
<h1>Galpao <%= @warehouse.code %></h1>
<div>
  <dt>Nome:</dt>
  <dd><%= @warehouse.name %></dd>
  <dt>Cidade:</dt>
  <dd><%= @warehouse.city %></dd>
  <dt>Area:</dt>
  <dd><%= @warehouse.area  %></dd>
  <dt>Endereco:</dt>
  <dd><%= @warehouse.address %></dd>
  <dt>CEP:</dt>
  <dd><%= @warehouse.cep %></dd>
  <dt>Descricao:</dt>
  <dd><%= @warehouse.description %></dd>
</div>
<%= link_to('Editar', edit_warehouse_path(@warehouse.id))%>
<%= link_to('Voltar', root_path)%>
<%= button_to('Remover', confirmar_exclusao_path(@warehouse.id), method: :get)%>